[package]
name = "pe-translator"
version = "1.0.0"
edition = "2021"
authors = ["Andree Salazar"]
description = "ADead-BIB Universal Binary Backend â€” PE/ELF/FsOS Generator"

[[bin]]
name = "pe-translator"
path = "src/main.rs"

[lib]
name = "pe_translator"
path = "src/lib.rs"

[dependencies]
